# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- job: macOS
  timeoutInMinutes: 360
  displayName: macOS
  # According to
  # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md
  # macOS-10.14 comes with Xcode 10.2.1
  pool:
    displayName: 'macOS 10.14'
    vmImage: 'macOS-10.14'
    demands: xcode
  steps:
  - script: 'brew install ninja cmake lrzip'
    displayName: 'Installing build dependencies'
  - script: |
      ./clone.sh
    displayName: 'Cloning Swift'
  - script: |
      ./build.sh
    displayName: 'Building Swift'
  - script: |
      ./package.sh
    displayName: 'Packaging Swift'
  - task: GitHubRelease@0
    displayName: 'Creating Github Release'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')
    inputs:
      gitHubConnection: GHRelease
      repositoryName: '$(Build.Repository.Name)'
      action: 'create' # Options: create, edit, delete
      target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: '$(Build.SourceVersion)-$(Build.BuildNumber)'
      assets: 'release/*'
      releaseNotesSource: 'file' # Optional. Options: file, input
      releaseNotesFile: 'checksums.md' # Optional
